### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by kkraune**
- we will not be able to easily auto-test this short term

### CODE REVIEW

**Comment by bratseth** [comment]
Did you try to feed with just with 6Gb?

**Comment by kkraune** [comment]
have not tried feeding yet, awaiting @jobergum . so we do not know but I will test it once ready. 6Gb is the default we use elsewhere

**Comment by bratseth** [comment]
I thought we upped it elsewhere ... let's wait for confirmation then. Having too little memory in the docker container fails in confusing ways.

**Comment by kkraune** [comment]
back to 10, so we can merge the rest

**Pull request merged**
