### PR TITLE
Fix typo in services.xml for basic-search-tensor

### PR DESCRIPTION
**Pull request by stiankri**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by bratseth** [comment]
Ouch. Thanks!
Did you sign the CLA?

**Comment by stiankri** [comment]
I'm waiting for my managers approval to sign the CLA.

**Comment by bratseth** [comment]
Ok, thanks. I think you need to make a comment here when it is done to cause the CLA check to re-run.

**Comment by stiankri** [comment]
I have now signed the CLA

**Comment by bratseth** [comment]
Thanks!

**Pull request merged**
