### PR TITLE
Add RAG sample app

### PR DESCRIPTION
**Pull request by lesters**
@kkraune, @andreer, @jobergum Please review.

Really smooth deploying to the cloud on GPU!

### CODE REVIEW

**Review by kkraune — APPROVED** [review]
💯  🎖️

**Review by jobergum — APPROVED** [review]
Great!

It would be great if the README had test instructions so it's a part of the testing routine, for the local, plus I would rather not have `docker/podman` and instead use `docker` like the rest of the sample apps as it will be easier to copy the commands. 

I'm looking at the ERROR: One or more files failed: commerce-product-ranking/README.md so it's unrelated to this PR

**Comment by jobergum** [comment]
Please update the `test/_test_config.yml` as well. I also think it would be easier if there could be one app package, schema is now duplicated in three places with slight modifications to services.xml.

**Comment by jobergum** [comment]
IMHO, There is no need to have 3 different deployment options, because they all work with the same services.xml file. For example https://github.com/vespa-engine/sample-apps/blob/master/colbert-long/services.xml and others demonstrate GPU and is still usable in single container setup.

**Comment by lesters** [comment]
@jobergum Good idea, I've unified the application and it probably works better now.

**Comment by jobergum** [comment]
Great job! Looks much easier now with fewer instructions! 🥇

**Pull request merged**
