### PR TITLE
Bergum/sample app issues

### PR DESCRIPTION
**Pull request by jobergum**
Remove pom.xml from none-java app and fix several wrong bundle names and correct services.xml syntax. This was causing 

* blog-recommendation to fail to start container
* boolean-search fail to start container & failed to configure due to wrong services.xml version nodes versus node

### CODE REVIEW

**Comment by jobergum** [comment]
FYI @bjorncs & @lesters. Doc also needs update where code examples are referenced with bundle names.

**Comment by jobergum** [comment]
Few more commits comming, please dont merge @bratseth yet.

**Comment by jobergum** [comment]
Done for now. Please review.

**Comment by bratseth** [comment]
Great!

**Pull request merged**
