### PR TITLE
Store Document from Processor

### PR DESCRIPTION
**Pull request by aguereca**
This PR is mainly to track an issue that I've seen when attempting to store DocumentOperations from a Processor, once issue addressed this can be merged and serve as reference to the community looking to implement this scenario.

### CODE REVIEW

**Comment by aguereca** [comment]
Issue filed on Vespa: https://github.com/vespa-engine/vespa/issues/5898

**Comment by bratseth** [comment]
This merely processes the documents - it never actually writes them to Vespa (which typically causes them to be processed, but also to be sent to the appropriate content clusters for storage).

To write documents from Java code, use the Document Access API:
http://docs.vespa.ai/documentation/document-api-guide.html#document-access

**Comment by aguereca** [comment]
Thanks for the quick response and the pointers, this is now working and ready to be used as reference for others.

**Comment by bratseth** [comment]
Great work!

**Pull request merged**
