### PR TITLE
Kkraune/remove redundant app

### PR DESCRIPTION
**Pull request by kkraune**
FYI @jonmv 

one less app to manage - the content of this is covered in other doc and sample apps

### CODE REVIEW

**Comment by jonmv** [comment]
We need to replace this app for use in the CD pipeline for our public system. I have a fork until then.

**Comment by kkraune** [comment]
can't we use album-recommendation-java in CD public? I see no instances for https://console.vespa-external-cd.aws.oath.cloud/tenant/vespa/application/basic-search/instance

**Comment by jonmv** [comment]
Yes, we can, but it needs to be done :)

**Comment by kkraune** [comment]
> We need to replace this app for use in the CD pipeline for our public system. I have a fork until then.

I need some help - I could not find any references to basic-search-hosted, probably looking in the wrong places.

We should not mix apps we use ourselves for testing with apps end users use for learning vespa. but maybe I got this all wrong - @jonmv  please let me know where I can go the make these changes

**Comment by jonmv** [comment]
I agree they should be separate. This app is used for the public cd pipeline because it was the only Vespa cloud-ified application at the time. A branch (hosted-cd) in this repository is the source. The application is `vespa.lalala`.

**Comment by kkraune** [comment]
I think @bjorncs now deploys album-recommendation for public CD and we can merge this now?

**Pull request merged**
